

---数据文件存放位置或者文件名，可根据实际环境修改
--1
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO1" DATAFILE '/opt/oracle/oradata/oradb/fltinfo1a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo1b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo1c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--2
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO2" DATAFILE '/opt/oracle/oradata/oradb/fltinfo2a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo2b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo2c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--3
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO3" DATAFILE '/opt/oracle/oradata/oradb/fltinfo3a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo3b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo3c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--4
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO4" DATAFILE '/opt/oracle/oradata/oradb/fltinfo4a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo4b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo4c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--5
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO5" DATAFILE '/opt/oracle/oradata/oradb/fltinfo5a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo5b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo5c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--6
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO6" DATAFILE '/opt/oracle/oradata/oradb/fltinfo6a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo6b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo6c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--7
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO7" DATAFILE '/opt/oracle/oradata/oradb/fltinfo7a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo7b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo7c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--8
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO8" DATAFILE '/opt/oracle/oradata/oradb/fltinfo8a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo8b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo8c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--9
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO9" DATAFILE '/opt/oracle/oradata/oradb/fltinfo9a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo9b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo9c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--10
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO10" DATAFILE '/opt/oracle/oradata/oradb/fltinfo10a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo10b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo10c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--11
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO11" DATAFILE '/opt/oracle/oradata/oradb/fltinfo11a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo11b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo11c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--12
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO12" DATAFILE '/opt/oracle/oradata/oradb/fltinfo12a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo12b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo12c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--13
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO13" DATAFILE '/opt/oracle/oradata/oradb/fltinfo13a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo13b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo13c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--14
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO14" DATAFILE '/opt/oracle/oradata/oradb/fltinfo14a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo14b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo14c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--15
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO15" DATAFILE '/opt/oracle/oradata/oradb/fltinfo15a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo15b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo15c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--16
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO16" DATAFILE '/opt/oracle/oradata/oradb/fltinfo16a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo16b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo16c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--17
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO17" DATAFILE '/opt/oracle/oradata/oradb/fltinfo17a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo17b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo17c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--18
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO18" DATAFILE '/opt/oracle/oradata/oradb/fltinfo18a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo18b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo18c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--19
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO19" DATAFILE '/opt/oracle/oradata/oradb/fltinfo19a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo19b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo19c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--20
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO20" DATAFILE '/opt/oracle/oradata/oradb/fltinfo20a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo20b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo20c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--21
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO21" DATAFILE '/opt/oracle/oradata/oradb/fltinfo21a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo21b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo21c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--22
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO22" DATAFILE '/opt/oracle/oradata/oradb/fltinfo22a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo22b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo22c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--23
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO23" DATAFILE '/opt/oracle/oradata/oradb/fltinfo23a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo23b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo23c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--24
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO24" DATAFILE '/opt/oracle/oradata/oradb/fltinfo24a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo24b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo24c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--25
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO25" DATAFILE '/opt/oracle/oradata/oradb/fltinfo25a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo25b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo25c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--26
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO26" DATAFILE '/opt/oracle/oradata/oradb/fltinfo26a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo26b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo26c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--27
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO27" DATAFILE '/opt/oracle/oradata/oradb/fltinfo27a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo27b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo27c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--28
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO28" DATAFILE '/opt/oracle/oradata/oradb/fltinfo28a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo28b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo28c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--29
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO29" DATAFILE '/opt/oracle/oradata/oradb/fltinfo29a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo29b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo29c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--30
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO30" DATAFILE '/opt/oracle/oradata/oradb/fltinfo30a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo30b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo30c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;


--31
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFO31" DATAFILE '/opt/oracle/oradata/oradb/fltinfo31a.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo31b.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFO1" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfo31c.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;



---创建索引表空间
--创建数据文件
CREATE SMALLFILE TABLESPACE "FLTINFOINDEX" DATAFILE '/opt/oracle/oradata/oradb/fltinfoindexa.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
--增加数据文件
ALTER TABLESPACE "FLTINFOINDEX" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfoindexb.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFOINDEX" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfoindexc.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFOINDEX" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfoindexd.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFOINDEX" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfoindexe.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFOINDEX" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfoindexf.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
ALTER TABLESPACE "FLTINFOINDEX" ADD DATAFILE '/opt/oracle/oradata/oradb/fltinfoindexg.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;




